export const SET_TDB_START = 'SET_TDB_START';
export const SET_TDB_SUCCESS = 'SET_TDB_SUCCESS';
export const SET_TDB__FAILED = 'SET_TDB__FAILED';

export const ADD_TASK_START = 'ADD_TASK_START';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const ADD_SUBTASK_START = 'ADD_SUBTASK_START';
export const ADD_SUBTASK_SUCCESS = 'ADD_SUBTASK_SUCCESS';
export const ADD_SUBTASK_FAILED = 'ADD_SUBTASK_FAILED';

export const RESET_ERROR = 'RESET_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const UNTOUCHED_DB = 'UNTOUCHED_DB';

export const SET_SELECTED_TASK = 'SET_SELECTED_TASK';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_TEMP_TIME = 'SET_TEMP_TIME';

export const FILL_TASK_START = 'FILL_TASK_START';
export const FILL_TASK_SUCCESS = 'FILL_TASK_SUCCESS';
export const FILL_TASK_FAILED = 'FILL_TASK__FAILED';

export const SET_TEMP_NODE = 'SET_TEMP_NODE';

export const SET_SELECTEDTASK_POINTER = 'SET_SELECTEDTASK_POINTER';

